services:
  mysql_db:
    image: "mysql:latest"
    restart: on-failure
    expose:
      - 3306
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: "testing"
    command: "mysqld --max-connections=8000"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 --password=$$MYSQL_ROOT_PASSWORD
      timeout: 60s
      retries: 20
      interval: 1s

  postgres_db:
    image: "postgres:latest"
    restart: on-failure
    expose:
      - 5432
    ports:
      - 5432:5432
    cap_add:
      - SYS_NICE
    environment:
      POSTGRES_PASSWORD: "my-secret-pw"
    command: "postgres -c shared_buffers=256MB -c max_connections=2000"
    healthcheck:
      test: pg_isready -q -d postgres -U postgres
      timeout: 60s
      retries: 10
      interval: 1s

  sqlsrv_db:
    image: "mcr.microsoft.com/mssql/server"
    restart: on-failure
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q "SELECT 1" || exit 1
      timeout: 60s
      retries: 10
      interval: 1s

  mongo_db:
    image: "mongo"
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 60s
      retries: 10
      interval: 1s
